# Generated by Django 4.2.7 on 2023-11-06 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Accepted', 'Accepted'), ('Preparing', 'Preparing'), ('Dispatched', 'Dispatched'), ('Delivered', 'Delivered')], default='Placed', max_length=15),
        ),
    ]
