# Generated by Django 4.2.7 on 2023-11-06 18:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0005_remove_order_created_at_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 6, 18, 44, 39, 845760, tzinfo=datetime.timezone.utc)),
        ),
    ]
