# Generated by Django 4.2.7 on 2023-11-07 11:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0009_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 11, 57, 36, 398992, tzinfo=datetime.timezone.utc)),
        ),
    ]
