# Generated by Django 4.2.7 on 2023-11-07 12:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizza_ordering', '0012_alter_order_order_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 11, 7, 12, 17, 45, 504767, tzinfo=datetime.timezone.utc)),
        ),
    ]
